apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: sheiley-shop-api
  name: sheiley-shop-api
spec:
  ports:
    - name: "5018"
      port: 5018
      targetPort: 80
  selector:
    io.kompose.service: sheiley-shop-api
status:
  loadBalancer: {}