apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  ports:
  - nodePort: 31001
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: backend
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - image: rodrigoarcos/backend-jenkins:66
        imagePullPolicy: IfNotPresent
        name: backend
        ports:
        - containerPort: 8000
